[package]
name = "rwm"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["blocks"]

[dependencies]
x11 = "2.21.0"
libc = "0.2.150"
yeslogic-fontconfig-sys = "5.0.0"
env_logger = "0.10.0"
log = "0.4.19"
